--- 

- name: set vars
  set_fact:
    cloudrc_dest: "/etc/kolla/triliovault-cloudrc"

- name: Copy Create Cloud Trust on OpenStack nodes
  template:
    src: create_cloud_trust.sh
    dest: "{{ item }}"
    mode: '0777'
  with_items:
    - "/tmp/create_cloud_trust.sh"

- name: Copy Triliovault-cloudrc on OpenStack nodes
  template:
    src: triliovault-cloudrc
    dest: "{{ item }}"
    mode: '0777'
  with_items:
    - "{{ cloudrc_dest }}"
  become: True

- name: Copy Create Cloud Trust on Ansible Node
  template:
    src: create_cloud_trust.sh
    dest: "{{ item }}"
    mode: '0777'
  with_items:
    - "/tmp/create_cloud_trust.sh"
  delegate_to: localhost

- name: Copy Triliovault-cloudrc on Ansible Node
  template:
    src: triliovault-cloudrc
    dest: "{{ item }}"
    mode: '0777'
  with_items:
    - "{{ cloudrc_dest }}"
  delegate_to: localhost
  become: True

- name: Verify triliovault-cloudrc is present or not
  stat: 
    path: "{{ cloudrc_dest }}"
  register: trilio_rc
  delegate_to: localhost
  become: True

- name: GET CLOUD_ADMIN_USER_ID
  shell: ". {{ cloudrc_dest }} && openstack user show --insecure --domain {{ cloud_admin_domainname }} -f value -c id {{ cloud_admin_username }}"
  register: admin_usr_id
  delegate_to: localhost
  when:
    - trilio_rc.stat.exists == true
  become: True

- set_fact:
    Cloud_Admin_UserID: "{{ admin_usr_id.stdout }}"

- name: GET CLOUD_UNIQUE_ID
  shell: ". {{ cloudrc_dest }} && openstack user show --insecure --domain default -f value -c id {{ triliovault_wlm_keystone_user }}"
  register: wlm_usr_id
  delegate_to: localhost
  when:
    - trilio_rc.stat.exists == true
  become: True

- set_fact:
    Triliovault_Wlm_User_ID: "{{ wlm_usr_id.stdout }}"
