---
- import_playbook: gather-facts.yml

# NOTE(mgoddard): In large environments, even tasks that are skipped can take a
# significant amount of time. This is an optimisation to prevent any tasks
# running in the subsequent plays for services that are disabled.
- name: Group hosts based on configuration
  hosts: all
  gather_facts: false
  max_fail_percentage: >-
    {{ group_hosts_max_fail_percentage |
       default(kolla_max_fail_percentage) |
       default(100) }}
  tasks:
    - name: Group hosts based on Kolla action
      group_by:
        key: "kolla_action_{{ kolla_action }}"
      changed_when: false

    - name: Group hosts based on enabled services
      group_by:
        key: "{{ item }}"
      changed_when: false
      with_items:
        - enable_aodh_{{ enable_aodh | bool }}
        - enable_barbican_{{ enable_barbican | bool }}
        - enable_blazar_{{ enable_blazar | bool }}
        - enable_ceilometer_{{ enable_ceilometer | bool }}
        - enable_ceph_rgw_{{ enable_ceph_rgw | bool }}
        - enable_cinder_{{ enable_cinder | bool }}
        - enable_cloudkitty_{{ enable_cloudkitty | bool }}
        - enable_collectd_{{ enable_collectd | bool }}
        - enable_cyborg_{{ enable_cyborg | bool }}
        - enable_designate_{{ enable_designate | bool }}
        - enable_etcd_{{ enable_etcd | bool }}
        - enable_glance_{{ enable_glance | bool }}
        - enable_gnocchi_{{ enable_gnocchi | bool }}
        - enable_grafana_{{ enable_grafana | bool }}
        - enable_hacluster_{{ enable_hacluster | bool }}
        - enable_heat_{{ enable_heat | bool }}
        - enable_horizon_{{ enable_horizon | bool }}
        - enable_influxdb_{{ enable_influxdb | bool }}
        - enable_ironic_{{ enable_ironic | bool }}
        - enable_iscsid_{{ enable_iscsid | bool }}
        - enable_keystone_{{ enable_keystone | bool }}
        - enable_kuryr_{{ enable_kuryr | bool }}
        - enable_letsencrypt_{{ enable_letsencrypt | bool }}
        - enable_loadbalancer_{{ enable_loadbalancer | bool }}
        - enable_magnum_{{ enable_magnum | bool }}
        - enable_manila_{{ enable_manila | bool }}
        - enable_mariadb_{{ enable_mariadb | bool }}
        - enable_masakari_{{ enable_masakari | bool }}
        - enable_memcached_{{ enable_memcached | bool }}
        - enable_mistral_{{ enable_mistral | bool }}
        - enable_multipathd_{{ enable_multipathd | bool }}
        - enable_neutron_{{ enable_neutron | bool }}
        - enable_nova_{{ enable_nova | bool }}
        - enable_octavia_{{ enable_octavia | bool }}
        - enable_opensearch_{{ enable_opensearch | bool }}
        - enable_opensearch_dashboards_{{ enable_opensearch_dashboards | bool }}
        - enable_openvswitch_{{ enable_openvswitch | bool }}_enable_ovs_dpdk_{{ enable_ovs_dpdk | bool }}
        - enable_ovn_{{ enable_ovn | bool }}
        - enable_placement_{{ enable_placement | bool }}
        - enable_prometheus_{{ enable_prometheus | bool }}
        - enable_rabbitmq_{{ enable_rabbitmq | bool }}
        - enable_redis_{{ enable_redis | bool }}
        - enable_skyline_{{ enable_skyline | bool }}
        - enable_swift_{{ enable_swift | bool }}
        - enable_tacker_{{ enable_tacker | bool }}
        - enable_telegraf_{{ enable_telegraf | bool }}
        - enable_trove_{{ enable_trove | bool }}
        - enable_venus_{{ enable_venus | bool }}
        - enable_watcher_{{ enable_watcher | bool }}
        - enable_zun_{{ enable_zun | bool }}
  tags: always

- name: Apply haproxy config for triliovault services
  gather_facts: false
  hosts:
    - loadbalancer
    - '&enable_loadbalancer_True'
  serial: '{{ kolla_serial|default("0") }}'
  tags:
    - haproxy
    - keepalived
    - loadbalancer
  roles:
    - { role: loadbalancer,
        when: enable_loadbalancer | bool }
  tasks:
    - include_role:
        name: triliovault-bobcat
        tasks_from: loadbalancer
      when:
        - inventory_hostname in groups['triliovault-datamover-api']
        - inventory_hostname in groups['triliovault-wlm-api']
        - enable_haproxy | bool
        - enable_triliovault | bool
        - kolla_action in ['deploy', 'reconfigure', 'upgrade', 'config']

- name: Apply role triliovault
  gather_facts: false
  hosts:
    - triliovault-datamover-api
    - triliovault-datamover
    - triliovault-wlm-api
    - triliovault-wlm-workloads
    - triliovault-wlm-scheduler
    - triliovault-wlm-cron
    - enable_triliovault | bool
  serial: '{{ kolla_serial|default("0") }}'
  roles:
    - { role: triliovault-bobcat,
        tags: triliovault,
        when: enable_triliovault | bool }
